db.log.drop()
db.createCollection("log")
db.log.createIndex({timestamp:-1})
db.log.createIndex({webrtc_id:1})
db.raw_peers.drop()
db.createCollection("raw_peers",{ capped : "true", size : 20000})
db.raw_peers.createIndex({webrtc_id:1,channel_id:1})
db.raw_peers.createIndex({channel_id:1})
db.raw_peers.createIndex({webrtc_id:1},{unique: true})
db.raw_peers.createIndex({unchecked:1})
