-- MySQL Script generated by MySQL Workbench
-- 08/30/16 16:58:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `p2p` ;

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p2p` DEFAULT CHARACTER SET utf8 ;
USE `p2p` ;

-- -----------------------------------------------------
-- Table `p2p`.`peer_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`peer_state` ;

CREATE TABLE IF NOT EXISTS `p2p`.`peer_state` (
  `webrtc_id` VARCHAR(45) NOT NULL,
  `channel_id` VARCHAR(45) NOT NULL,
  `gg_id` VARCHAR(45) NULL,
  `last_update` INT NULL,
  `ip` INT NOT NULL,
  `network` INT NOT NULL,
  `netmask` INT NOT NULL,
  `asn` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `webrtc_id` ON `p2p`.`peer_state` (`webrtc_id` ASC);

CREATE UNIQUE INDEX `uniq_id` ON `p2p`.`peer_state` (`webrtc_id` ASC, `channel_id` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO p2p;
 DROP USER p2p;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'p2p' IDENTIFIED BY 'wb5nv6d8';

GRANT ALL ON `p2p`.* TO 'p2p';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
