#!/bin/bash

#rvm reload;rvm default ruby 2.4

COMMON_ONLINE_PEERS_WORKERS=2
PEER_LIST_MASTER_WORKERS=1
PEER_LIST_SLAVE_WORKERS=2
PEER_LOG_WORKERS=8
OFFLINE_PEERS_WORKERS=1
SLOW_ONLINE_PEERS_WORKERS=1

ruby /home/mihailov.s/miker_p2p/etc/zabbix.rb
